new node knex test and vite test

diff --git a/.github/workflows/examples-test.yml b/.github/workflows/examples-test.yml
--- a/.github/workflows/examples-test.yml
+++ b/.github/workflows/examples-test.yml
@@ -19,6 +19,9 @@ jobs:
         with:
           deno-version: vx.x.x
 
+      - name: setup playwright for browser related test
+        run: npx playwright install --with-deps && npx playwright install msedge && npx playwright install chrome
+
       - name: build driver
         run: npm i && npm run build
 
@@ -147,6 +150,21 @@ jobs:
       - name: remove with-plain-javascript
         run: rm -rf examples/with-plain-javascript
 
+      - name: node with-typescript-knex
+        working-directory: examples/with-typescript-knex
+        run: |
+          npm i
+          node_test=$(npx tsx example.ts)
+
+          if [[ "$node_test" == *"\"Company\": \"Embraer - Empresa Brasileira de Aeronáutica S.A.\","* ]]; then
+            echo "✅ node with-typescript-knex test passed"
+            exit 0
+          fi
+          echo "❌ node with-typescript-knex test failed"
+          exit 1
+        env:
+          DATABASE_URL: ${{ secrets.CHINOOK_DATABASE_URL }}
+
       - name: bun with-typescript-knex
         working-directory: examples/with-typescript-knex
         run: |
@@ -221,3 +239,25 @@ jobs:
 
       - name: remove with-typescript-nextjs
         run: rm -rf examples/with-typescript-nextjs
+
+      - name: node with-javascript-vite
+        working-directory: examples/with-javascript-vite
+        run: npm i && npx playwright test
+        env:
+          VITE_DATABASE_URL: ${{ secrets.CHINOOK_DATABASE_URL }}
+
+      - name: bun with-javascript-vite
+        working-directory: examples/with-javascript-vite
+        run: bun i && bun playwright test
+        env:
+          VITE_DATABASE_URL: ${{ secrets.CHINOOK_DATABASE_URL }}
+
+      - name: deno with-javascript-vite
+        working-directory: examples/with-javascript-vite
+        run: exit 0 #deno add npm:@playwright/test && deno run --allow-all npm:playwright test
+        env:
+          VITE_DATABASE_URL: ${{ secrets.CHINOOK_DATABASE_URL }}
+          PW_DISABLE_TS_ESM: true
+
+      - name: remove with-javascript-vite
+        run: rm -rf examples/with-javascript-vite
